# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[47,  0],
       [97, 88],
       [41, 49],
       [11, 87],
       [78, 33],
       [62, 73],
       [ 2, 74],
       [59, 34],
       [56, 56],
       [73, 18]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

/root/miniconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[ 0.47368421,  0.        ],
       [ 1.        ,  1.        ],
       [ 0.41052632,  0.55681818],
       [ 0.09473684,  0.98863636],
       [ 0.8       ,  0.375     ],
       [ 0.63157895,  0.82954545],
       [ 0.        ,  0.84090909],
       [ 0.6       ,  0.38636364],
       [ 0.56842105,  0.63636364],
       [ 0.74736842,  0.20454545]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

/root/miniconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[ 0.47368421,  0.        ],
       [ 1.        ,  1.        ],
       [ 0.41052632,  0.55681818],
       [ 0.09473684,  0.98863636],
       [ 0.8       ,  0.375     ],
       [ 0.63157895,  0.82954545],
       [ 0.        ,  0.84090909],
       [ 0.6       ,  0.38636364],
       [ 0.56842105,  0.63636364],
       [ 0.74736842,  0.20454545]])

In [20]:
import pandas as pd

In [21]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [24]:
data.head()

f1  f2  f3  label
0  79  12  96     29
1  35  75  39     84
2   5  61  62     87
3  97  85  76     69
4  67  65  30     64

In [25]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [28]:
X_train.shape

(35, 3)

In [29]:
X_test.shape

(15, 3)

In [30]:
y_train.shape

(35,)

In [31]:
y_test.shape

(15,)

## Great Job!